import { Inter } from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'

import { LayoutProvider } from './lib/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><LayoutProvider>{children}</LayoutProvider></body>
    </html>
  )
}
